# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
 
target 'realtimechatios' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
 
    # Pods for realtimechatios
    pod 'Starscream','~> 3.0.4'
    pod 'MessageKit','~> 0.13.1'
    pod 'Alamofire','~> 4.7.0'
 
end